### ISSUE TITLE
Throws error when list of menu items is empty

### ISSUE THREAD

**Issue by ksk100** [nescalante/knockout.contextmenu#10]
I'll take a look at this issue too if that's helpful @nescalante?

I rewound to `0.3.1` just to double check it wasn't introduced with the other fix I pushed.  But if the list of items for the menu is an empty array (as opposed to uninitialised at all), then we get the following:

```
Uncaught TypeError: Cannot read property 'style' of undefined
    openMenu @ knockout.contextmenu-0.3.1.js:105
```

**Comment by nescalante** [comment]
fixed, thanks for contributing

**Comment by ksk100** [comment]
Cool thanks
